name: Quality Assurance

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  run:
    name: Quality Assurance
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12', '14']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm run test
#      - run: npm run lerna -- bootstrap
#      - run: npm run lerna -- exec -- npm run build
#      - run: npm run lerna -- exec -- npm run test --coverage-text

