name: Quality Assurance

 on:
   pull_requests:
     paths-ignore:
       - '**/*.md'
   push:
     branches:
       - main
     paths-ignore:
       - '**/*.md'

jobs:
  run:
    name: Quality Assurance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
          with:
            node-version: '12'
      - run: npm ci
      - run: npm run lerna -- bootstrap
      - run: npm run lerna -- exec -- npm run test --coverage-text

